<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pais;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder {

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {

        // Nombre del pais
        // abreviatura ISO del pais
        // codigo ANSI del pais

        DB::table('paises')->insert([
                ['nombre' => 'España', 'codigoISO' => 'ESP', 'codigoANSI' => '724'],
                ['nombre' => 'Afganistán', 'codigoISO' => 'AFG', 'codigoANSI' => '4'],
                ['nombre' => 'Aland Islands', 'codigoISO' => 'ALI', 'codigoANSI' => '248'],
                ['nombre' => 'Albania', 'codigoISO' => 'ALB', 'codigoANSI' => '8'],
                ['nombre' => 'Alemania', 'codigoISO' => 'DEU', 'codigoANSI' => '276'],
                ['nombre' => 'Andorra', 'codigoISO' => 'AND', 'codigoANSI' => '20'],
                ['nombre' => 'Angola', 'codigoISO' => 'AGO', 'codigoANSI' => '24'],
                ['nombre' => 'Anguila', 'codigoISO' => 'AIA', 'codigoANSI' => '660'],
                ['nombre' => 'Antártida', 'codigoISO' => 'ATA', 'codigoANSI' => '10'],
                ['nombre' => 'Antigua y Barbuda', 'codigoISO' => 'ATG', 'codigoANSI' => '28'],
                ['nombre' => 'Antillas Neerlandesas', 'codigoISO' => 'ANT', 'codigoANSI' => '530'],
                ['nombre' => 'Arabia Saudita', 'codigoISO' => 'SAU', 'codigoANSI' => '682'],
                ['nombre' => 'Argelia', 'codigoISO' => 'DZA', 'codigoANSI' => '12'],
                ['nombre' => 'Argentina', 'codigoISO' => 'ARG', 'codigoANSI' => '32'],
                ['nombre' => 'Armenia', 'codigoISO' => 'ARM', 'codigoANSI' => '51'],
                ['nombre' => 'Aruba', 'codigoISO' => 'ABW', 'codigoANSI' => '533'],
                ['nombre' => 'Australia', 'codigoISO' => 'AUS', 'codigoANSI' => '36'],
                ['nombre' => 'Austria', 'codigoISO' => 'AUT', 'codigoANSI' => '40'],
                ['nombre' => 'Azerbaiyán', 'codigoISO' => 'AZE', 'codigoANSI' => '31'],
                ['nombre' => 'Bahamas', 'codigoISO' => 'BHS', 'codigoANSI' => '44'],
                ['nombre' => 'Bahrein', 'codigoISO' => 'BHR', 'codigoANSI' => '48'],
                ['nombre' => 'Bangladesh', 'codigoISO' => 'BGD', 'codigoANSI' => '50'],
                ['nombre' => 'Barbados', 'codigoISO' => 'BRB', 'codigoANSI' => '52'],
                ['nombre' => 'Belarús', 'codigoISO' => 'BLR', 'codigoANSI' => '112'],
                ['nombre' => 'Bélgica', 'codigoISO' => 'BEL', 'codigoANSI' => '56'],
                ['nombre' => 'Bélgica-Luxemburgo', 'codigoISO' => 'BLX', 'codigoANSI' => '58'],
                ['nombre' => 'Belice', 'codigoISO' => 'BLZ', 'codigoANSI' => '84'],
                ['nombre' => 'Benin', 'codigoISO' => 'BEN', 'codigoANSI' => '204'],
                ['nombre' => 'Bermudas', 'codigoISO' => 'BMU', 'codigoANSI' => '60'],
                ['nombre' => 'Bhután', 'codigoISO' => 'BTN', 'codigoANSI' => '64'],
                ['nombre' => 'Bolivia', 'codigoISO' => 'BOL', 'codigoANSI' => '68'],
                ['nombre' => 'Bonaire', 'codigoISO' => 'BES', 'codigoANSI' => '535'],
                ['nombre' => 'Bosnia y Herzegovina', 'codigoISO' => 'BIH', 'codigoANSI' => '70'],
                ['nombre' => 'Botswana', 'codigoISO' => 'BWA', 'codigoANSI' => '72'],
                ['nombre' => 'Brasil', 'codigoISO' => 'BRA', 'codigoANSI' => '76'],
                ['nombre' => 'Brunei Darussalam', 'codigoISO' => 'BRN', 'codigoANSI' => '96'],
                ['nombre' => 'Bulgaria', 'codigoISO' => 'BGR', 'codigoANSI' => '100'],
                ['nombre' => 'Burkina Faso', 'codigoISO' => 'BFA', 'codigoANSI' => '854'],
                ['nombre' => 'Burundi', 'codigoISO' => 'BDI', 'codigoANSI' => '108'],
                ['nombre' => 'Cabo Verde', 'codigoISO' => 'CPV', 'codigoANSI' => '132'],
                ['nombre' => 'Camboya', 'codigoISO' => 'KHM', 'codigoANSI' => '116'],
                ['nombre' => 'Camerún', 'codigoISO' => 'CMR', 'codigoANSI' => '120'],
                ['nombre' => 'Canadá', 'codigoISO' => 'CAN', 'codigoANSI' => '124'],
                ['nombre' => 'Categorías especiales', 'codigoISO' => 'SPE', 'codigoANSI' => '839'],
                ['nombre' => 'Chad', 'codigoISO' => 'TCD', 'codigoANSI' => '148'],
                ['nombre' => 'Checoslovaquia', 'codigoISO' => 'CSK', 'codigoANSI' => '200'],
                ['nombre' => 'Chile', 'codigoISO' => 'CHL', 'codigoANSI' => '152'],
                ['nombre' => 'China', 'codigoISO' => 'CHN', 'codigoANSI' => '156'],
                ['nombre' => 'Chipre', 'codigoISO' => 'CYP', 'codigoANSI' => '196'],
                ['nombre' => 'Colombia', 'codigoISO' => 'COL', 'codigoANSI' => '170'],
                ['nombre' => 'Comando I del Pacífico de Estados Unidos', 'codigoISO' => 'USP', 'codigoANSI' => '849'],
                ['nombre' => 'Comoras', 'codigoISO' => 'COM', 'codigoANSI' => '174'],
                ['nombre' => 'Congo,  Rep. del', 'codigoISO' => 'COG', 'codigoANSI' => '178'],
                ['nombre' => 'Congo,  Rep. Dem. del', 'codigoISO' => 'ZAR', 'codigoANSI' => '180'],
                ['nombre' => 'Corea,  Rep. de', 'codigoISO' => 'KOR', 'codigoANSI' => '410'],
                ['nombre' => 'Corea,  Rep. Dem. de', 'codigoISO' => 'PRK', 'codigoANSI' => '408'],
                ['nombre' => 'Costa Rica', 'codigoISO' => 'CRI', 'codigoANSI' => '188'],
                ['nombre' => 'Côte d\'Ivoire', 'codigoISO' => 'CIV', 'codigoANSI' => '384'],
                ['nombre' => 'Croacia', 'codigoISO' => 'HRV', 'codigoANSI' => '191'],
                ['nombre' => 'Cuba', 'codigoISO' => 'CUB', 'codigoANSI' => '192'],
                ['nombre' => 'Curacao', 'codigoISO' => 'CUW', 'codigoANSI' => '531'],
                ['nombre' => 'Dinamarca', 'codigoISO' => 'DNK', 'codigoANSI' => '208'],
                ['nombre' => 'Djibouti', 'codigoISO' => 'DJI', 'codigoANSI' => '262'],
                ['nombre' => 'Dominica', 'codigoISO' => 'DMA', 'codigoANSI' => '212'],
                ['nombre' => 'Ecuador', 'codigoISO' => 'ECU', 'codigoANSI' => '218'],
                ['nombre' => 'Egipto,  Rep. Árabe de', 'codigoISO' => 'EGY', 'codigoANSI' => '818'],
                ['nombre' => 'El Salvador', 'codigoISO' => 'SLV', 'codigoANSI' => '222'],
                ['nombre' => 'Emiratos Árabes Unidos', 'codigoISO' => 'ARE', 'codigoANSI' => '784'],
                ['nombre' => 'Eritrea', 'codigoISO' => 'ERI', 'codigoANSI' => '232'],
                ['nombre' => 'Eslovenia', 'codigoISO' => 'SVN', 'codigoANSI' => '705'],
                ['nombre' => 'Estados Unidos', 'codigoISO' => 'USA', 'codigoANSI' => '840'],
                ['nombre' => 'Estonia', 'codigoISO' => 'EST', 'codigoANSI' => '233'],
                ['nombre' => 'Etiopía (excluida Eritrea)', 'codigoISO' => 'ETH', 'codigoANSI' => '231'],
                ['nombre' => 'Etiopía (incluida Eritrea)', 'codigoISO' => 'ETF', 'codigoANSI' => '230'],
                ['nombre' => 'European Union', 'codigoISO' => 'EUN', 'codigoANSI' => '918'],
                ['nombre' => 'Ex Sudán', 'codigoISO' => 'SDN', 'codigoANSI' => '736'],
                ['nombre' => 'Federación de Rusia', 'codigoISO' => 'RUS', 'codigoANSI' => '643'],
                ['nombre' => 'Fiji', 'codigoISO' => 'FJI', 'codigoANSI' => '242'],
                ['nombre' => 'Filipinas', 'codigoISO' => 'PHL', 'codigoANSI' => '608'],
                ['nombre' => 'Finlandia', 'codigoISO' => 'FIN', 'codigoANSI' => '246'],
                ['nombre' => 'Fm Panama Cz', 'codigoISO' => 'PCZ', 'codigoANSI' => '592'],
                ['nombre' => 'Fm Rhod Nyas', 'codigoISO' => 'ZW1', 'codigoANSI' => '717'],
                ['nombre' => 'Fm Tanganyik', 'codigoISO' => 'TAN', 'codigoANSI' => '835'],
                ['nombre' => 'Fm Vietnam DR', 'codigoISO' => 'VDR', 'codigoANSI' => '866'],
                ['nombre' => 'Fm Vietnam Rp', 'codigoISO' => 'SVR', 'codigoANSI' => '868'],
                ['nombre' => 'Fm Zanz-Pemb', 'codigoISO' => 'ZPM', 'codigoANSI' => '836'],
                ['nombre' => 'Francia', 'codigoISO' => 'FRA', 'codigoANSI' => '250'],
                ['nombre' => 'Gabón', 'codigoISO' => 'GAB', 'codigoANSI' => '266'],
                ['nombre' => 'Gambia', 'codigoISO' => 'GMB', 'codigoANSI' => '270'],
                ['nombre' => 'Gaza Strip', 'codigoISO' => 'GAZ', 'codigoANSI' => '274'],
                ['nombre' => 'Georgia', 'codigoISO' => 'GEO', 'codigoANSI' => '268'],
                ['nombre' => 'Ghana', 'codigoISO' => 'GHA', 'codigoANSI' => '288'],
                ['nombre' => 'Gibraltar', 'codigoISO' => 'GIB', 'codigoANSI' => '292'],
                ['nombre' => 'Granada', 'codigoISO' => 'GRD', 'codigoANSI' => '308'],
                ['nombre' => 'Grecia', 'codigoISO' => 'GRC', 'codigoANSI' => '300'],
                ['nombre' => 'Groenlandia', 'codigoISO' => 'GRL', 'codigoANSI' => '304'],
                ['nombre' => 'Guadalupe', 'codigoISO' => 'GLP', 'codigoANSI' => '312'],
                ['nombre' => 'Guam', 'codigoISO' => 'GUM', 'codigoANSI' => '316'],
                ['nombre' => 'Guatemala', 'codigoISO' => 'GTM', 'codigoANSI' => '320'],
                ['nombre' => 'Guayana Francesa', 'codigoISO' => 'GUF', 'codigoANSI' => '254'],
                ['nombre' => 'Guinea', 'codigoISO' => 'GIN', 'codigoANSI' => '324'],
                ['nombre' => 'Guinea Ecuatorial', 'codigoISO' => 'GNQ', 'codigoANSI' => '226'],
                ['nombre' => 'Guinea-Bissau', 'codigoISO' => 'GNB', 'codigoANSI' => '624'],
                ['nombre' => 'Guyana', 'codigoISO' => 'GUY', 'codigoANSI' => '328'],
                ['nombre' => 'Haití', 'codigoISO' => 'HTI', 'codigoANSI' => '332'],
                ['nombre' => 'Honduras', 'codigoISO' => 'HND', 'codigoANSI' => '340'],
                ['nombre' => 'Hong Kong (China)', 'codigoISO' => 'HKG', 'codigoANSI' => '344'],
                ['nombre' => 'Hungría', 'codigoISO' => 'HUN', 'codigoANSI' => '348'],
                ['nombre' => 'India', 'codigoISO' => 'IND', 'codigoANSI' => '356'],
                ['nombre' => 'Indonesia', 'codigoISO' => 'IDN', 'codigoANSI' => '360'],
                ['nombre' => 'Irán,  Rep. Islámica del', 'codigoISO' => 'IRN', 'codigoANSI' => '364'],
                ['nombre' => 'Iraq', 'codigoISO' => 'IRQ', 'codigoANSI' => '368'],
                ['nombre' => 'Irlanda', 'codigoISO' => 'IRL', 'codigoANSI' => '372'],
                ['nombre' => 'Isla Bouvet', 'codigoISO' => 'BVT', 'codigoANSI' => '74'],
                ['nombre' => 'Isla Bunker', 'codigoISO' => 'BUN', 'codigoANSI' => '837'],
                ['nombre' => 'Isla de Navidad', 'codigoISO' => 'CXR', 'codigoANSI' => '162'],
                ['nombre' => 'Isla Norfolk', 'codigoISO' => 'NFK', 'codigoANSI' => '574'],
                ['nombre' => 'Islandia', 'codigoISO' => 'ISL', 'codigoANSI' => '352'],
                ['nombre' => 'Islas Caimán', 'codigoISO' => 'CYM', 'codigoANSI' => '136'],
                ['nombre' => 'Islas Cocos (Keeling)', 'codigoISO' => 'CCK', 'codigoANSI' => '166'],
                ['nombre' => 'Islas Cook', 'codigoISO' => 'COK', 'codigoANSI' => '184'],
                ['nombre' => 'Islas del Pacífico', 'codigoISO' => 'PCE', 'codigoANSI' => '582'],
                ['nombre' => 'Islas Falkland', 'codigoISO' => 'FLK', 'codigoANSI' => '238'],
                ['nombre' => 'Islas Feroe', 'codigoISO' => 'FRO', 'codigoANSI' => '234'],
                ['nombre' => 'Islas Georgias del Sur y Sandwich del Sur', 'codigoISO' => 'SGS', 'codigoANSI' => '239'],
                ['nombre' => 'Islas Heard y McDonald', 'codigoISO' => 'HMD', 'codigoANSI' => '334'],
                ['nombre' => 'Islas Marshall', 'codigoISO' => 'MHL', 'codigoANSI' => '584'],
                ['nombre' => 'Islas Salomón', 'codigoISO' => 'SLB', 'codigoANSI' => '90'],
                ['nombre' => 'Islas Turcas y Caicos', 'codigoISO' => 'TCA', 'codigoANSI' => '796'],
                ['nombre' => 'Islas Ultramarinas Menores de Estados Unidos', 'codigoISO' => 'UMI', 'codigoANSI' => '581'],
                ['nombre' => 'Islas Vírgenes (EE.UU.)', 'codigoISO' => 'VIR', 'codigoANSI' => '850'],
                ['nombre' => 'Islas Vírgenes Británicas', 'codigoISO' => 'VGB', 'codigoANSI' => '92'],
                ['nombre' => 'Islas Wallis y Futuna', 'codigoISO' => 'WLF', 'codigoANSI' => '876'],
                ['nombre' => 'Israel', 'codigoISO' => 'ISR', 'codigoANSI' => '376'],
                ['nombre' => 'Italia', 'codigoISO' => 'ITA', 'codigoANSI' => '380'],
                ['nombre' => 'Jamaica', 'codigoISO' => 'JAM', 'codigoANSI' => '388'],
                ['nombre' => 'Japón', 'codigoISO' => 'JPN', 'codigoANSI' => '392'],
                ['nombre' => 'Jhonston Island', 'codigoISO' => 'JTN', 'codigoANSI' => '396'],
                ['nombre' => 'Jordania', 'codigoISO' => 'JOR', 'codigoANSI' => '400'],
                ['nombre' => 'Kazajstán', 'codigoISO' => 'KAZ', 'codigoANSI' => '398'],
                ['nombre' => 'Kenya', 'codigoISO' => 'KEN', 'codigoANSI' => '404'],
                ['nombre' => 'Kirguistán', 'codigoISO' => 'KGZ', 'codigoANSI' => '417'],
                ['nombre' => 'Kiribati', 'codigoISO' => 'KIR', 'codigoANSI' => '296'],
                ['nombre' => 'Kosovo', 'codigoISO' => 'KSV', 'codigoANSI' => '412'],
                ['nombre' => 'Kuwait', 'codigoISO' => 'KWT', 'codigoANSI' => '414'],
                ['nombre' => 'Lesotho', 'codigoISO' => 'LSO', 'codigoANSI' => '426'],
                ['nombre' => 'Letonia', 'codigoISO' => 'LVA', 'codigoANSI' => '428'],
                ['nombre' => 'Líbano', 'codigoISO' => 'LBN', 'codigoANSI' => '422'],
                ['nombre' => 'Liberia', 'codigoISO' => 'LBR', 'codigoANSI' => '430'],
                ['nombre' => 'Libia', 'codigoISO' => 'LBY', 'codigoANSI' => '434'],
                ['nombre' => 'Liechtenstein', 'codigoISO' => 'LIE', 'codigoANSI' => '438'],
                ['nombre' => 'Lituania', 'codigoISO' => 'LTU', 'codigoANSI' => '440'],
                ['nombre' => 'Luxemburgo', 'codigoISO' => 'LUX', 'codigoANSI' => '442'],
                ['nombre' => 'Macao', 'codigoISO' => 'MAC', 'codigoANSI' => '446'],
                ['nombre' => 'Macedonia,  ex Rep. Yugoslava de', 'codigoISO' => 'MKD', 'codigoANSI' => '807'],
                ['nombre' => 'Madagascar', 'codigoISO' => 'MDG', 'codigoANSI' => '450'],
                ['nombre' => 'Malasia', 'codigoISO' => 'MYS', 'codigoANSI' => '458'],
                ['nombre' => 'Malawi', 'codigoISO' => 'MWI', 'codigoANSI' => '454'],
                ['nombre' => 'Maldivas', 'codigoISO' => 'MDV', 'codigoANSI' => '462'],
                ['nombre' => 'Malí', 'codigoISO' => 'MLI', 'codigoANSI' => '466'],
                ['nombre' => 'Malta', 'codigoISO' => 'MLT', 'codigoANSI' => '470'],
                ['nombre' => 'Mariana', 'codigoISO' => 'MNP', 'codigoANSI' => '580'],
                ['nombre' => 'Marruecos', 'codigoISO' => 'MAR', 'codigoANSI' => '504'],
                ['nombre' => 'Martinica', 'codigoISO' => 'MTQ', 'codigoANSI' => '474'],
                ['nombre' => 'Mauricio', 'codigoISO' => 'MUS', 'codigoANSI' => '480'],
                ['nombre' => 'Mauritania', 'codigoISO' => 'MRT', 'codigoANSI' => '478'],
                ['nombre' => 'Mayotte', 'codigoISO' => 'MYT', 'codigoANSI' => '175'],
                ['nombre' => 'México', 'codigoISO' => 'MEX', 'codigoANSI' => '484'],
                ['nombre' => 'Micronesia,  Estados Fed. de', 'codigoISO' => 'FSM', 'codigoANSI' => '583'],
                ['nombre' => 'Midway Islands', 'codigoISO' => 'MID', 'codigoANSI' => '488'],
                ['nombre' => 'Mónaco', 'codigoISO' => 'MCO', 'codigoANSI' => '492'],
                ['nombre' => 'Mongolia', 'codigoISO' => 'MNG', 'codigoANSI' => '496'],
                ['nombre' => 'Montenegro', 'codigoISO' => 'MNT', 'codigoANSI' => '499'],
                ['nombre' => 'Montserrat', 'codigoISO' => 'MSR', 'codigoANSI' => '500'],
                ['nombre' => 'Mozambique', 'codigoISO' => 'MOZ', 'codigoANSI' => '508'],
                ['nombre' => 'Mundo', 'codigoISO' => 'WLD', 'codigoANSI' => '0'],
                ['nombre' => 'Myanmar', 'codigoISO' => 'MMR', 'codigoANSI' => '104'],
                ['nombre' => 'Namibia', 'codigoISO' => 'NAM', 'codigoANSI' => '516'],
                ['nombre' => 'Nauru', 'codigoISO' => 'NRU', 'codigoANSI' => '520'],
                ['nombre' => 'Nepal', 'codigoISO' => 'NPL', 'codigoANSI' => '524'],
                ['nombre' => 'Nicaragua', 'codigoISO' => 'NIC', 'codigoANSI' => '558'],
                ['nombre' => 'Níger', 'codigoISO' => 'NER', 'codigoANSI' => '562'],
                ['nombre' => 'Nigeria', 'codigoISO' => 'NGA', 'codigoANSI' => '566'],
                ['nombre' => 'Niue', 'codigoISO' => 'NIU', 'codigoANSI' => '570'],
                ['nombre' => 'No especificados', 'codigoISO' => 'UNS', 'codigoANSI' => '898'],
                ['nombre' => 'Noruega', 'codigoISO' => 'NOR', 'codigoANSI' => '578'],
                ['nombre' => 'Nueva Caledonia', 'codigoISO' => 'NCL', 'codigoANSI' => '540'],
                ['nombre' => 'Nueva Zelandia', 'codigoISO' => 'NZL', 'codigoANSI' => '554'],
                ['nombre' => 'Omán', 'codigoISO' => 'OMN', 'codigoANSI' => '512'],
                ['nombre' => 'Otra zona de Asia,  no esp.', 'codigoISO' => 'OAS', 'codigoANSI' => '490'],
                ['nombre' => 'Países Bajos', 'codigoISO' => 'NLD', 'codigoANSI' => '528'],
                ['nombre' => 'Pakistán', 'codigoISO' => 'PAK', 'codigoANSI' => '586'],
                ['nombre' => 'Palau', 'codigoISO' => 'PLW', 'codigoANSI' => '585'],
                ['nombre' => 'Panamá', 'codigoISO' => 'PAN', 'codigoANSI' => '591'],
                ['nombre' => 'Papua Nueva Guinea', 'codigoISO' => 'PNG', 'codigoANSI' => '598'],
                ['nombre' => 'Paraguay', 'codigoISO' => 'PRY', 'codigoANSI' => '600'],
                ['nombre' => 'Pen Malaysia', 'codigoISO' => 'PMY', 'codigoANSI' => '459'],
                ['nombre' => 'Perú', 'codigoISO' => 'PER', 'codigoANSI' => '604'],
                ['nombre' => 'Pitcairn', 'codigoISO' => 'PCN', 'codigoANSI' => '612'],
                ['nombre' => 'Polinesia Francesa', 'codigoISO' => 'PYF', 'codigoANSI' => '258'],
                ['nombre' => 'Polonia', 'codigoISO' => 'POL', 'codigoANSI' => '616'],
                ['nombre' => 'Portugal', 'codigoISO' => 'PRT', 'codigoANSI' => '620'],
                ['nombre' => 'Puerto Rico', 'codigoISO' => 'PRI', 'codigoANSI' => '630'],
                ['nombre' => 'Qatar', 'codigoISO' => 'QAT', 'codigoANSI' => '634'],
                ['nombre' => 'Reino Unido', 'codigoISO' => 'GBR', 'codigoANSI' => '826'],
                ['nombre' => 'República Árabe Siria', 'codigoISO' => 'SYR', 'codigoANSI' => '760'],
                ['nombre' => 'República Centroafricana', 'codigoISO' => 'CAF', 'codigoANSI' => '140'],
                ['nombre' => 'República Checa', 'codigoISO' => 'CZE', 'codigoANSI' => '203'],
                ['nombre' => 'República de Moldova', 'codigoISO' => 'MDA', 'codigoANSI' => '498'],
                ['nombre' => 'República Democrática Alemana', 'codigoISO' => 'DDR', 'codigoANSI' => '278'],
                ['nombre' => 'República Democrática Popular Lao', 'codigoISO' => 'LAO', 'codigoANSI' => '418'],
                ['nombre' => 'República Dominicana', 'codigoISO' => 'DOM', 'codigoANSI' => '214'],
                ['nombre' => 'República Eslovaca', 'codigoISO' => 'SVK', 'codigoANSI' => '703'],
                ['nombre' => 'Reunión', 'codigoISO' => 'REU', 'codigoANSI' => '638'],
                ['nombre' => 'Rumania', 'codigoISO' => 'ROM', 'codigoANSI' => '642'],
                ['nombre' => 'Rwanda', 'codigoISO' => 'RWA', 'codigoANSI' => '646'],
                ['nombre' => 'Ryukyu Is', 'codigoISO' => 'RYU', 'codigoANSI' => '647'],
                ['nombre' => 'Sabah', 'codigoISO' => 'SBH', 'codigoANSI' => '461'],
                ['nombre' => 'Sahara Occidental', 'codigoISO' => 'ESH', 'codigoANSI' => '732'],
                ['nombre' => 'Saint Kitts y Nevis', 'codigoISO' => 'KNA', 'codigoANSI' => '659'],
                ['nombre' => 'Saint Kitts-Nevis-Anguilla-Aru', 'codigoISO' => 'KN1', 'codigoANSI' => '658'],
                ['nombre' => 'Samoa', 'codigoISO' => 'WSM', 'codigoANSI' => '882'],
                ['nombre' => 'Samoa Americana', 'codigoISO' => 'ASM', 'codigoANSI' => '16'],
                ['nombre' => 'San Marino', 'codigoISO' => 'SMR', 'codigoANSI' => '674'],
                ['nombre' => 'San Martín', 'codigoISO' => 'SXM', 'codigoANSI' => '534'],
                ['nombre' => 'San Pedro y Miquelón', 'codigoISO' => 'SPM', 'codigoANSI' => '666'],
                ['nombre' => 'San Vicente y las Granadinas', 'codigoISO' => 'VCT', 'codigoANSI' => '670'],
                ['nombre' => 'Santa Elena', 'codigoISO' => 'SHN', 'codigoANSI' => '654'],
                ['nombre' => 'Santa Lucía', 'codigoISO' => 'LCA', 'codigoANSI' => '662'],
                ['nombre' => 'Santa Sede', 'codigoISO' => 'VAT', 'codigoANSI' => '336'],
                ['nombre' => 'Santo Tomé y Príncipe', 'codigoISO' => 'STP', 'codigoANSI' => '678'],
                ['nombre' => 'Sarawak', 'codigoISO' => 'SWK', 'codigoANSI' => '457'],
                ['nombre' => 'Senegal', 'codigoISO' => 'SEN', 'codigoANSI' => '686'],
                ['nombre' => 'Serbia,  Rep. Fed. de (Serbia y Montenegro)', 'codigoISO' => 'SER', 'codigoANSI' => '891'],
                ['nombre' => 'Seychelles', 'codigoISO' => 'SYC', 'codigoANSI' => '690'],
                ['nombre' => 'Sierra Leona', 'codigoISO' => 'SLE', 'codigoANSI' => '694'],
                ['nombre' => 'SIKKIM', 'codigoISO' => 'SIK', 'codigoANSI' => '698'],
                ['nombre' => 'Singapur', 'codigoISO' => 'SGP', 'codigoANSI' => '702'],
                ['nombre' => 'Somalia', 'codigoISO' => 'SOM', 'codigoANSI' => '706'],
                ['nombre' => 'Sri Lanka', 'codigoISO' => 'LKA', 'codigoANSI' => '144'],
                ['nombre' => 'Sudáfrica', 'codigoISO' => 'ZAF', 'codigoANSI' => '710'],
                ['nombre' => 'Sudán', 'codigoISO' => 'SUD', 'codigoANSI' => '729'],
                ['nombre' => 'Sudán del Sur', 'codigoISO' => 'SSD', 'codigoANSI' => '728'],
                ['nombre' => 'Suecia', 'codigoISO' => 'SWE', 'codigoANSI' => '752'],
                ['nombre' => 'Suiza', 'codigoISO' => 'CHE', 'codigoANSI' => '756'],
                ['nombre' => 'Suriname', 'codigoISO' => 'SUR', 'codigoANSI' => '740'],
                ['nombre' => 'Svalbard and Jan Mayen Is', 'codigoISO' => 'SJM', 'codigoANSI' => '744'],
                ['nombre' => 'Swazilandia', 'codigoISO' => 'SWZ', 'codigoANSI' => '748'],
                ['nombre' => 'Tailandia', 'codigoISO' => 'THA', 'codigoANSI' => '764'],
                ['nombre' => 'Taiwán,  China', 'codigoISO' => 'TWN', 'codigoANSI' => '158'],
                ['nombre' => 'Tanzanía', 'codigoISO' => 'TZA', 'codigoANSI' => '834'],
                ['nombre' => 'Tayikistán', 'codigoISO' => 'TJK', 'codigoANSI' => '762'],
                ['nombre' => 'Territorio Antártico Británico', 'codigoISO' => 'BAT', 'codigoANSI' => '80'],
                ['nombre' => 'Territorio Británico del Océano Índico', 'codigoISO' => 'IOT', 'codigoANSI' => '86'],
                ['nombre' => 'Territorio Palestino Ocupado', 'codigoISO' => 'PSE', 'codigoANSI' => '275'],
                ['nombre' => 'Tierras Australes y Antárticas Francesas', 'codigoISO' => 'ATF', 'codigoANSI' => '260'],
                ['nombre' => 'Timor Oriental', 'codigoISO' => 'TMP', 'codigoANSI' => '626'],
                ['nombre' => 'Togo', 'codigoISO' => 'TGO', 'codigoANSI' => '768'],
                ['nombre' => 'Tokelau', 'codigoISO' => 'TKL', 'codigoANSI' => '772'],
                ['nombre' => 'Tonga', 'codigoISO' => 'TON', 'codigoANSI' => '776'],
                ['nombre' => 'Trinidad y Tobago', 'codigoISO' => 'TTO', 'codigoANSI' => '780'],
                ['nombre' => 'Túnez', 'codigoISO' => 'TUN', 'codigoANSI' => '788'],
                ['nombre' => 'Turkmenistán', 'codigoISO' => 'TKM', 'codigoANSI' => '795'],
                ['nombre' => 'Turquía', 'codigoISO' => 'TUR', 'codigoANSI' => '792'],
                ['nombre' => 'Tuvalu', 'codigoISO' => 'TUV', 'codigoANSI' => '798'],
                ['nombre' => 'Ucrania', 'codigoISO' => 'UKR', 'codigoANSI' => '804'],
                ['nombre' => 'Uganda', 'codigoISO' => 'UGA', 'codigoANSI' => '800'],
                ['nombre' => 'Unión Soviética', 'codigoISO' => 'SVU', 'codigoANSI' => '810'],
                ['nombre' => 'Uruguay', 'codigoISO' => 'URY', 'codigoANSI' => '858'],
                ['nombre' => 'Uzbekistán', 'codigoISO' => 'UZB', 'codigoANSI' => '860'],
                ['nombre' => 'Vanuatu', 'codigoISO' => 'VUT', 'codigoANSI' => '548'],
                ['nombre' => 'Venezuela', 'codigoISO' => 'VEN', 'codigoANSI' => '862'],
                ['nombre' => 'Viet Nam', 'codigoISO' => 'VNM', 'codigoANSI' => '704'],
                ['nombre' => 'Wake Island', 'codigoISO' => 'WAK', 'codigoANSI' => '872'],
                ['nombre' => 'Yemen,  Rep. del', 'codigoISO' => 'YEM', 'codigoANSI' => '887'],
                ['nombre' => 'Yemen,  Rep. Dem. Del', 'codigoISO' => 'YDR', 'codigoANSI' => '720'],
                ['nombre' => 'Yugoslavia,  Rep. Fed. de (Serbia y Montenegro)', 'codigoISO' => 'YUG', 'codigoANSI' => '890'],
                ['nombre' => 'Zambia', 'codigoISO' => 'ZMB', 'codigoANSI' => '894'],
                ['nombre' => 'Zimbabwe', 'codigoISO' => 'ZWE', 'codigoANSI' => '716'],
        ]);
    }

}
